;;;请证明，如果将a和b的序对表示为乘积(2^a)*(3^b)对应的整数，我们就可以只用非负整数和算术运算表示序对。请给出对应的过程cons、car和cdr的定义。
(define (cons x y)
  (* (expt 2 x)
     (expt 3 y)))
(define (car x)
  (if (= 0 (remainder x 2))
      (+ 1 (car (/ x 2)))
      0))
(define (cdr x)
  (if (= 0 (remainder x 3))
      (+ 1 (cdr (/ x 3)))
      0))
